/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as Essential1000RouteImport } from './routes/essential-1000'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HomeRouteImport } from './routes/home'
import { Route as KnowledgeMapRouteImport } from './routes/knowledge-map'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ConceptSlugRouteImport } from './routes/concept.$slug'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as LessonSlugRouteImport } from './routes/lesson.$slug'
import { Route as PathSlugRouteImport } from './routes/path.$slug'
import { Route as TimelineEventSlugRouteImport } from './routes/timeline.$eventSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const Essential1000Route = Essential1000RouteImport.update({
  id: '/essential-1000',
  path: '/essential-1000',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeMapRoute = KnowledgeMapRouteImport.update({
  id: '/knowledge-map',
  path: '/knowledge-map',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptSlugRoute = ConceptSlugRouteImport.update({
  id: '/concept/$slug',
  path: '/concept/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonSlugRoute = LessonSlugRouteImport.update({
  id: '/lesson/$slug',
  path: '/lesson/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PathSlugRoute = PathSlugRouteImport.update({
  id: '/path/$slug',
  path: '/path/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineEventSlugRoute = TimelineEventSlugRouteImport.update({
  id: '/$eventSlug',
  path: '/$eventSlug',
  getParentRoute: () => TimelineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/essential-1000': typeof Essential1000Route
  '/explore': typeof ExploreRoute
  '/glossary': typeof GlossaryRoute
  '/home': typeof HomeRoute
  '/knowledge-map': typeof KnowledgeMapRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/paths': typeof PathsRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/concept/$slug': typeof ConceptSlugRoute
  '/course/$slug': typeof CourseSlugRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/timeline/$eventSlug': typeof TimelineEventSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/essential-1000': typeof Essential1000Route
  '/explore': typeof ExploreRoute
  '/glossary': typeof GlossaryRoute
  '/home': typeof HomeRoute
  '/knowledge-map': typeof KnowledgeMapRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/paths': typeof PathsRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/concept/$slug': typeof ConceptSlugRoute
  '/course/$slug': typeof CourseSlugRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/timeline/$eventSlug': typeof TimelineEventSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/essential-1000': typeof Essential1000Route
  '/explore': typeof ExploreRoute
  '/glossary': typeof GlossaryRoute
  '/home': typeof HomeRoute
  '/knowledge-map': typeof KnowledgeMapRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/paths': typeof PathsRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/concept/$slug': typeof ConceptSlugRoute
  '/course/$slug': typeof CourseSlugRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/path/$slug': typeof PathSlugRoute
  '/timeline/$eventSlug': typeof TimelineEventSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/essential-1000'
    | '/explore'
    | '/glossary'
    | '/home'
    | '/knowledge-map'
    | '/learn'
    | '/library'
    | '/login'
    | '/onboarding'
    | '/paths'
    | '/profile'
    | '/review'
    | '/search'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/category/$slug'
    | '/concept/$slug'
    | '/course/$slug'
    | '/lesson/$slug'
    | '/path/$slug'
    | '/timeline/$eventSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/essential-1000'
    | '/explore'
    | '/glossary'
    | '/home'
    | '/knowledge-map'
    | '/learn'
    | '/library'
    | '/login'
    | '/onboarding'
    | '/paths'
    | '/profile'
    | '/review'
    | '/search'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/category/$slug'
    | '/concept/$slug'
    | '/course/$slug'
    | '/lesson/$slug'
    | '/path/$slug'
    | '/timeline/$eventSlug'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/essential-1000'
    | '/explore'
    | '/glossary'
    | '/home'
    | '/knowledge-map'
    | '/learn'
    | '/library'
    | '/login'
    | '/onboarding'
    | '/paths'
    | '/profile'
    | '/review'
    | '/search'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/category/$slug'
    | '/concept/$slug'
    | '/course/$slug'
    | '/lesson/$slug'
    | '/path/$slug'
    | '/timeline/$eventSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  Essential1000Route: typeof Essential1000Route
  ExploreRoute: typeof ExploreRoute
  GlossaryRoute: typeof GlossaryRoute
  HomeRoute: typeof HomeRoute
  KnowledgeMapRoute: typeof KnowledgeMapRoute
  LearnRoute: typeof LearnRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PathsRoute: typeof PathsRoute
  ProfileRoute: typeof ProfileRoute
  ReviewRoute: typeof ReviewRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TimelineRoute: typeof TimelineRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  ConceptSlugRoute: typeof ConceptSlugRoute
  CourseSlugRoute: typeof CourseSlugRoute
  LessonSlugRoute: typeof LessonSlugRoute
  PathSlugRoute: typeof PathSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essential-1000': {
      id: '/essential-1000'
      path: '/essential-1000'
      fullPath: '/essential-1000'
      preLoaderRoute: typeof Essential1000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-map': {
      id: '/knowledge-map'
      path: '/knowledge-map'
      fullPath: '/knowledge-map'
      preLoaderRoute: typeof KnowledgeMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$slug': {
      id: '/concept/$slug'
      path: '/concept/$slug'
      fullPath: '/concept/$slug'
      preLoaderRoute: typeof ConceptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$slug': {
      id: '/lesson/$slug'
      path: '/lesson/$slug'
      fullPath: '/lesson/$slug'
      preLoaderRoute: typeof LessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$slug': {
      id: '/path/$slug'
      path: '/path/$slug'
      fullPath: '/path/$slug'
      preLoaderRoute: typeof PathSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$eventSlug': {
      id: '/timeline/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/timeline/$eventSlug'
      preLoaderRoute: typeof TimelineEventSlugRouteImport
      parentRoute: typeof TimelineRoute
    }
  }
}

interface TimelineRouteChildren {
  TimelineEventSlugRoute: typeof TimelineEventSlugRoute
}

const TimelineRouteChildren: TimelineRouteChildren = {
  TimelineEventSlugRoute: TimelineEventSlugRoute,
}

const TimelineRouteWithChildren = TimelineRoute._addFileChildren(
  TimelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  Essential1000Route: Essential1000Route,
  ExploreRoute: ExploreRoute,
  GlossaryRoute: GlossaryRoute,
  HomeRoute: HomeRoute,
  KnowledgeMapRoute: KnowledgeMapRoute,
  LearnRoute: LearnRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PathsRoute: PathsRoute,
  ProfileRoute: ProfileRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TimelineRoute: TimelineRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  ConceptSlugRoute: ConceptSlugRoute,
  CourseSlugRoute: CourseSlugRoute,
  LessonSlugRoute: LessonSlugRoute,
  PathSlugRoute: PathSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
